// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Print3dMarketplace.PrintersAPI.EF;

#nullable disable

namespace Print3dMarketplace.PrintersAPI.Migrations
{
    [DbContext(typeof(PrintersDbContext))]
    partial class PrintersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Print3dMarketplace.PrintersAPI.Entities.Nozzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nozzles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6166c1a4-dd1d-4949-b322-3501d7081720"),
                            Size = "0.2mm Nozzle"
                        },
                        new
                        {
                            Id = new Guid("83d84d40-e1f7-4934-b378-914e95cc13aa"),
                            Size = "0.3mm Nozzle"
                        },
                        new
                        {
                            Id = new Guid("f7c066e1-e400-494f-8715-5c765ae97d13"),
                            Size = "0.4mm Nozzle"
                        },
                        new
                        {
                            Id = new Guid("368f3f6e-a75a-4062-8cdd-3dd58aa54c68"),
                            Size = "0.5mm Nozzle"
                        },
                        new
                        {
                            Id = new Guid("2a5606d3-d4c2-49e9-9ac9-515a9e405241"),
                            Size = "0.6mm Nozzle"
                        },
                        new
                        {
                            Id = new Guid("fbf46e86-ebc2-4cf7-b26a-d7c13e82a926"),
                            Size = "0.8mm Nozzle"
                        },
                        new
                        {
                            Id = new Guid("a467d589-f2bd-4641-aa16-18dc6baaed87"),
                            Size = "1.0mm Nozzle"
                        });
                });

            modelBuilder.Entity("Print3dMarketplace.PrintersAPI.Entities.TemplatePrinter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrintAreaHeight")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaLength")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaWidth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TemplatePrinters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b24a4905-d77e-489d-97e6-341ca23fbda3"),
                            ModelName = "Ender i3",
                            PrintAreaHeight = 150.0,
                            PrintAreaLength = 150.0,
                            PrintAreaWidth = 150.0
                        },
                        new
                        {
                            Id = new Guid("c21da304-81fc-4d9f-a8ab-8897fcd8ed6d"),
                            ModelName = "Prusa 360",
                            PrintAreaHeight = 200.0,
                            PrintAreaLength = 200.0,
                            PrintAreaWidth = 200.0
                        },
                        new
                        {
                            Id = new Guid("7893477c-0a20-418b-9a42-7ec2ada17a72"),
                            ModelName = "Anet 300",
                            PrintAreaHeight = 300.0,
                            PrintAreaLength = 300.0,
                            PrintAreaWidth = 300.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
