// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Print3dMarketplace.PrintRequestsAPI.EF;

#nullable disable

namespace Print3dMarketplace.PrintRequestsAPI.Migrations
{
    [DbContext(typeof(PrintRequestsDbContext))]
    [Migration("20231213103344_Update_PrintRequest_Entity")]
    partial class Update_PrintRequest_Entity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Infill")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("LayerHeight")
                        .HasColumnType("float");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PrintAreaHeight")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaLength")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaWidth")
                        .HasColumnType("float");

                    b.Property<Guid>("PrintRequestStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("UseSupports")
                        .HasColumnType("bit");

                    b.Property<double?>("WallThickness")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PrintRequestStatusId");

                    b.ToTable("PrintRequests");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrintRequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a5f7bf59-9553-4634-989d-a36701c26c51"),
                            Name = "Undefined"
                        },
                        new
                        {
                            Id = new Guid("d53a5231-574f-40d8-b440-bc0297bcb582"),
                            Name = "New"
                        },
                        new
                        {
                            Id = new Guid("f4f2e6a7-090b-4668-880b-ceddf8695c60"),
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = new Guid("54aa8111-d4b4-4fa3-970c-73d26414e2c1"),
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("252986fb-f903-4eed-af7f-d9da58c17a26"),
                            Name = "CreatorSubmission"
                        },
                        new
                        {
                            Id = new Guid("352fccfc-a0f1-49ff-9a72-512d634c1d93"),
                            Name = "UserSubmission"
                        },
                        new
                        {
                            Id = new Guid("70efccfc-ab1f-41f7-bd0e-6ddfab8d4845"),
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.HasOne("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", "PrintRequestStatus")
                        .WithMany()
                        .HasForeignKey("PrintRequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintRequestStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
