// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Print3dMarketplace.PrintRequestsAPI.EF;

#nullable disable

namespace Print3dMarketplace.PrintRequestsAPI.Migrations
{
    [DbContext(typeof(PrintRequestsDbContext))]
    [Migration("20231216193402_Add_SubmittedCreators_Migration")]
    partial class Add_SubmittedCreators_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Infill")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("LayerHeight")
                        .HasColumnType("float");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PrintAreaHeight")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaLength")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaWidth")
                        .HasColumnType("float");

                    b.Property<Guid>("PrintRequestStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("UseSupports")
                        .HasColumnType("bit");

                    b.Property<double?>("WallThickness")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PrintRequestStatusId");

                    b.ToTable("PrintRequests");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrintRequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("caa358bc-528d-4726-a604-0069d0bf0b7c"),
                            Name = "Undefined"
                        },
                        new
                        {
                            Id = new Guid("eb854489-fed9-4184-b1c5-3374281db69c"),
                            Name = "New"
                        },
                        new
                        {
                            Id = new Guid("d728b2bb-2dc6-45bd-a12b-d75f46a31f6f"),
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = new Guid("0775c063-d5e6-4d1c-ae0f-42b41cd1607e"),
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("10b30331-3e10-439d-b7e1-0930cabb8164"),
                            Name = "CreatorSubmission"
                        },
                        new
                        {
                            Id = new Guid("204b833f-a545-42b5-8869-510d9d2c2b79"),
                            Name = "UserSubmission"
                        },
                        new
                        {
                            Id = new Guid("7b37c506-2712-412d-8db3-92be344cb802"),
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.SubmittedCreator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrintRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrintRequestId");

                    b.ToTable("SubmittedCreators");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.HasOne("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", "PrintRequestStatus")
                        .WithMany()
                        .HasForeignKey("PrintRequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintRequestStatus");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.SubmittedCreator", b =>
                {
                    b.HasOne("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", "PrintRequest")
                        .WithMany("SubmittedCreators")
                        .HasForeignKey("PrintRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintRequest");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.Navigation("SubmittedCreators");
                });
#pragma warning restore 612, 618
        }
    }
}
