// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Print3dMarketplace.PrintRequestsAPI.EF;

#nullable disable

namespace Print3dMarketplace.PrintRequestsAPI.Migrations
{
    [DbContext(typeof(PrintRequestsDbContext))]
    [Migration("20231217143438_Add_CustomerSubmittedCreator_migration")]
    partial class Add_CustomerSubmittedCreator_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerSubmittedCreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Infill")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("LayerHeight")
                        .HasColumnType("float");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PrintAreaHeight")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaLength")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaWidth")
                        .HasColumnType("float");

                    b.Property<Guid>("PrintRequestStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("UseSupports")
                        .HasColumnType("bit");

                    b.Property<double?>("WallThickness")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PrintRequestStatusId");

                    b.ToTable("PrintRequests");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrintRequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9896da6e-6748-440c-a8e3-a2acb8c69876"),
                            Name = "Undefined"
                        },
                        new
                        {
                            Id = new Guid("0b0a26bf-a0c9-4549-8e64-026176cc7dcf"),
                            Name = "New"
                        },
                        new
                        {
                            Id = new Guid("ab44cb20-bd9f-4186-a694-4550998ae583"),
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = new Guid("83a02861-cdb9-4448-9d81-6737003c2051"),
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("9f74103b-0a68-45d6-a4e0-a8c6d0872a6c"),
                            Name = "CreatorSubmission"
                        },
                        new
                        {
                            Id = new Guid("00338f01-69dc-487f-ae62-0665df103b07"),
                            Name = "UserSubmission"
                        },
                        new
                        {
                            Id = new Guid("86d7a658-7585-4531-9ad8-9f26cf173540"),
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.SubmittedCreator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrintRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrintRequestId");

                    b.ToTable("SubmittedCreators");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.HasOne("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", "PrintRequestStatus")
                        .WithMany()
                        .HasForeignKey("PrintRequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintRequestStatus");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.SubmittedCreator", b =>
                {
                    b.HasOne("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", "PrintRequest")
                        .WithMany("SubmittedCreators")
                        .HasForeignKey("PrintRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintRequest");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.Navigation("SubmittedCreators");
                });
#pragma warning restore 612, 618
        }
    }
}
