// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Print3dMarketplace.PrintRequestsAPI.EF;

#nullable disable

namespace Print3dMarketplace.PrintRequestsAPI.Migrations
{
    [DbContext(typeof(PrintRequestsDbContext))]
    partial class PrintRequestsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerSubmittedCreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Infill")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("LayerHeight")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaHeight")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaLength")
                        .HasColumnType("float");

                    b.Property<double>("PrintAreaWidth")
                        .HasColumnType("float");

                    b.Property<Guid>("PrintRequestStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("UseSupports")
                        .HasColumnType("bit");

                    b.Property<double?>("WallThickness")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PrintRequestStatusId");

                    b.ToTable("PrintRequests");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrintRequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b4a0daa-3d27-4d7f-aaaa-fb23732c0e80"),
                            Name = "Undefined"
                        },
                        new
                        {
                            Id = new Guid("127ab3c8-907d-45f8-af20-181130a06fd5"),
                            Name = "New"
                        },
                        new
                        {
                            Id = new Guid("52241bda-b8b4-42ca-bc69-169f3b913359"),
                            Name = "Canceled"
                        },
                        new
                        {
                            Id = new Guid("725488bc-a383-412b-a167-740322c931f3"),
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("2b618945-d6c2-4519-85af-8e4af9ae41c5"),
                            Name = "CreatorSubmission"
                        },
                        new
                        {
                            Id = new Guid("46a9c9c7-26ce-44dc-8746-74eb82a20f2e"),
                            Name = "UserSubmission"
                        },
                        new
                        {
                            Id = new Guid("01be8f83-ad78-47bc-a1e4-e064f4871c1b"),
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.SubmittedCreator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrintRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrintRequestId");

                    b.ToTable("SubmittedCreators");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.HasOne("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequestStatus", "PrintRequestStatus")
                        .WithMany()
                        .HasForeignKey("PrintRequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintRequestStatus");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.SubmittedCreator", b =>
                {
                    b.HasOne("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", "PrintRequest")
                        .WithMany("SubmittedCreators")
                        .HasForeignKey("PrintRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrintRequest");
                });

            modelBuilder.Entity("Print3dMarketplace.PrintRequestsAPI.Entities.PrintRequest", b =>
                {
                    b.Navigation("SubmittedCreators");
                });
#pragma warning restore 612, 618
        }
    }
}
