// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Print3dMarketplace.MaterialsAPI.EF;

#nullable disable

namespace Print3dMarketplace.MaterialsAPI.Migrations
{
    [DbContext(typeof(MaterialsDbContext))]
    partial class MaterialsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Print3dMarketplace.MaterialsAPI.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0681bc6c-ca63-4039-a516-36c7e4fa70fb"),
                            Name = "Red"
                        },
                        new
                        {
                            Id = new Guid("075c35c2-a807-4d92-bd7d-6e701e4b8b6e"),
                            Name = "Green"
                        },
                        new
                        {
                            Id = new Guid("88169965-e520-4157-a3d6-e54dab403aae"),
                            Name = "Blue"
                        },
                        new
                        {
                            Id = new Guid("7b185938-1877-4433-b0f4-b8588ee01d56"),
                            Name = "White"
                        });
                });

            modelBuilder.Entity("Print3dMarketplace.MaterialsAPI.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TemplateMaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("TemplateMaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Print3dMarketplace.MaterialsAPI.Entities.TemplateMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TemplateMaterials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bffc7b83-c6d2-4490-ab6a-e1fe7d08b230"),
                            Name = "ABS"
                        },
                        new
                        {
                            Id = new Guid("8bbd3668-026e-4f95-8a2b-5939d02dda66"),
                            Name = "PLA"
                        },
                        new
                        {
                            Id = new Guid("9c64981b-5b80-4064-a9bb-25debecb38a4"),
                            Name = "PETG"
                        });
                });

            modelBuilder.Entity("Print3dMarketplace.MaterialsAPI.Entities.Material", b =>
                {
                    b.HasOne("Print3dMarketplace.MaterialsAPI.Entities.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Print3dMarketplace.MaterialsAPI.Entities.TemplateMaterial", "TemplateMaterial")
                        .WithMany()
                        .HasForeignKey("TemplateMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("TemplateMaterial");
                });
#pragma warning restore 612, 618
        }
    }
}
